version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    # If your app reads a local resume file at runtime, mount it here:
    # volumes:
    #   - ./data:/app/data:ro
