export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import "./globals.scss";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="preconnect" href="https://fonts.googleapis.com"></link>
      <link
        rel="preconnect"
        href="https://fonts.gstatic.com"
        crossorigin
      ></link>
      <link
        href="https://fonts.googleapis.com/css2?family=Lexend+Deca:wght@100..900&family=Manrope:wght@200..800&display=swap"
        rel="stylesheet"
      ></link>
      <body>{children}</body>
    </html>
  );
}
